name: scilake-enrichments
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - tqdm
  - openblas
  - pytorch
  - pip:
      - gliner==0.2.22
      - transformers==4.51.0
      - accelerate>=0.29.0,<1.0
      - tokenizers>=0.21.0,<0.23.0
      - spacy>=3.7.2
      - scispacy
      - rdflib
      - torch>=2.2.0
      - safetensors